name: dotnet-api
services:
  api:
    image: mcr.microsoft.com/dotnet/aspnet:9.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app  # Mapeia a pasta 'src' para '/app' dentro do container
    working_dir: /app  # Define o diretório de trabalho dentro do container como '/app'
    ports:
      - "5000:5000"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=YourPassword123!
      - MYSQL_DATABASE=MyDb
    ports:
      - "3399:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  sql_data:
    driver: local
  mysql_data:
    driver: local
